### ISSUE TITLE
Stack trace converting problem user preferences to sexpr

### ISSUE THREAD

**Issue by tcmitchell** [SD2E/xplan_api#1]
The code below demonstrates a stack trace I see when converting a problem to an s-expression.

```python
from xplan_api.sexpr_conversion import to_s_expr
import xplan_api.preferences as pref
import xplan_api.problem as prob

preferences = [
    pref.user_preference([pref.request_measurement_for("cavoigt",
                                                       "transform")])
]

problem = prob.problem("bug", "bug", preferences, None, None)

# This causes a stack trace
to_s_expr(problem)
```

Stack trace:

```
Traceback (most recent call last):
  File "sexpr_bug.py", line 13, in <module>
    to_s_expr(problem)
  File "/Users/tmitchel/Projects/sd2/xplan_api/xplan_api/sexpr_conversion.py", line 161, in to_s_expr
    return conversion_fn(data)
  File "/Users/tmitchel/Projects/sd2/xplan_api/xplan_api/sexpr_conversion.py", line 145, in problem
    preferences="\n".join([to_s_expr(x) for x in data["preferences"]]),
  File "/Users/tmitchel/Projects/sd2/xplan_api/xplan_api/sexpr_conversion.py", line 161, in to_s_expr
    return conversion_fn(data)
  File "/Users/tmitchel/Projects/sd2/xplan_api/xplan_api/sexpr_conversion.py", line 137, in user_preference
    to_s_expr(data["preference"])
  File "/Users/tmitchel/Projects/sd2/xplan_api/xplan_api/sexpr_conversion.py", line 159, in to_s_expr
    data_type = data["type"]
TypeError: list indices must be integers, not str
```

**Comment by danbryce** [comment]
I think this is obsolete.
